# Generated by Django 4.2.2 on 2023-06-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Наименование датчика"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Описание датчика"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(verbose_name="Температура")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sensor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="measurement.sensor",
                        verbose_name="ID датчика",
                    ),
                ),
            ],
        ),
    ]
